name: snapweb
base: core
version: 0.26-11-dev
summary: Beautiful and functional interface for snap management
description: |
  This service allows you to manage your Ubuntu Core device from a web interface or REST API.

  Features include:

  - manage updates to the system.
  - control the state of other snappy packages.
  - browse the store to install new snappy packages.

  Please find the source code for this snap at:
  https://github.com/snapcore/snapweb
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

plugs:
  dot-snap-auth-file:
    interface: personal-files
    read:
    - $HOME/.snap
    write:
    - $HOME/.snap
  etc-passwd:
    interface: system-files
    read:
      - /etc/passwd

apps:
  snapweb:
    command: bin/snapweb
    daemon: simple
    plugs:
      - network
      - network-bind
      - timeserver-control
      - dot-snap-auth-file
      - snapd-control
      - etc-passwd
  generate-token:
    command: bin/generate-token

parts:
  snapweb:
    plugin: godeps
    source: .
    go-importpath: github.com/snapcore/snapweb
    build-packages: [gcc]
  snapweb-ui:
    plugin: gulp
    gulp-tasks:
      - 'default' 
      - 'install'
    gulp-version: 3.9.1
    node-engine: 10.23.0
    override-build: |
      sed -i '/karma-phantom/d' package.json
    source: .
    build-packages:
      - git
      - python
      - g++
      - build-essential
    override-prime: |
      cp -R $SNAPCRAFT_STAGE/../project/parts/snapweb-ui/install/www $SNAPCRAFT_PRIME/
