name: snapweb
version: 0.26-10
summary: Beautiful and functional interface for snap management
description: |
  This service allows you to manage your Ubuntu Core device from a web interface or REST API.

  Features include:

  - manage updates to the system.
  - control the state of other snappy packages.
  - browse the store to install new snappy packages.

  Please find the source code for this snap at:
  https://github.com/snapcore/snapweb
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  snapweb:
    command: bin/snapweb
    daemon: simple
    plugs:
      - network
      - network-bind
      - snapd-control
      - timeserver-control
  generate-token:
    command: bin/generate-token

parts:
  snapweb:
    plugin: godeps
    source: .
    go-importpath: github.com/snapcore/snapweb
    build-packages: [gcc]
  snapweb-ui:
    plugin: gulp
    node-engine: 6.11.0
    gulp-tasks: ['install']
    prepare: |
      sed -i '/karma-phantom/d' package.json
    source: .
    build-packages:
      - git
      - python
      - g++
      - build-essential

