#!/bin/sh

# snappy-magic-launch - a stub that finds the right multiarch binary and sets all the right
#                       environment variables when launching multiarch snapps
#
# Usage:
#   - copy this stub in the snapp bin/ directory with the name matching the multiarch binary
set -e

# avahi daemon specific options
config="avahi-daemon.conf"
# This is a workaround for not having the env vars available
version=$(/bin/grep 'version:' meta/package.yaml | /bin/sed -e 's/version: *//')
config_path="/var/lib/apps/webdm/$version/$config"

[ ! -f "$config_path" ] && /bin/cp "$config" "$config_path"

verbose=false
platform=$(uname -i)
plat_abi=

# map platform to multiarch triplet - manually
case $platform in
  x86_64)
    plat_abi=x86_64-linux-gnu
    ;;
  armv7l)
    plat_abi=arm-linux-gnueabihf
    ;;
  *)
    echo "unknown platform for snappy-magic: $platform. remember to file a bug or better yet: fix it :)"
    ;;
esac

# runtime
snapp_bin_path=$0
snapp_bin=$(basename $snapp_bin_path)
snapp_dir=$(realpath $(dirname $snapp_bin_path)/)
snapp_name=$(echo $snapp_bin | sed -e 's/\(.*\)[.]\([^.]*\)$/\1/g')
snapp_org_bin=$(echo $snapp_bin | sed -e 's/\(.*\)[.]\([^.]*\)$/\2/g')

$verbose && echo snapp_name: $snapp_name
$verbose && echo snapp_bin: $snapp_bin
$verbose && echo snapp_dir: $snapp_dir
$verbose && echo snapp_org_bin: $snapp_org_bin
$verbose && echo plat_abi: $plat_abi

PATH="$snapp_dir/bin/$plat_abi/:$PATH"
LD_LIBRARY_PATH="$snapp_dir/lib/$plat_abi/:$LD_LIBRARY_PATH"
export PATH LD_LIBRARY_PATH

# make cwd the snapp dir
cd $snapp_dir

# fire the binary
$verbose && echo PATH is $PATH
$verbose && echo LD_LIBRARY_PATH is $LD_LIBRARY_PATH
$verbose && echo launching $snapp_bin "$@"
exec $snapp_bin -f "$config_path" "$@"

# never reach this
exit 1
