#!/bin/sh
set -e

platform=$(uname -i)

case $platform in
    x86_64)
        plat_abi=x86_64-linux-gnu
        ;;
    armv7l)
        plat_abi=arm-linux-gnueabihf
        ;;
    aarch64)
        plat_abi=aarch64-linux-gnu
        ;;
    *)
        echo "unknown platform for snappy-magic: $platform. remember to file a bug or better yet: fix it :)"
        ;;
esac

mkdir -m1777 -p $SNAP_APP_TMPDIR
exec $SNAP_APP_PATH/bin/$plat_abi/snappyd

# never reach this
exit 1
