#!/bin/sh
set -e

platform=$(uname -i)

case $platform in
    x86_64)
        arch=x86_64-linux-gnu
        ;;
    armv7l)
        arch=arm-linux-gnueabihf
        ;;
    *)
        echo "unknown platform for snappy-magic: $platform. remember to file a bug or better yet: fix it :)"
        ;;
esac

exec $SNAP_APP_PATH/bin/$arch/snappyd

# never reach this
exit 1
